### ISSUE TITLE
support fMP4 with vp9

### ISSUE THREAD

**Issue by nintha** [alfg/mp4-inspector#3]
I try to upload a fragmented mp4 file with vp9 codec. However, it prints some errors in the console.
![image](https://user-images.githubusercontent.com/22030293/105593301-d1889480-5dcd-11eb-8daa-214b9c8de8ca.png)

Could mp4-inspector support fMP4 with vp9? 
Thx.

**Comment by alfg** [comment]
Hi @nintha, 

I don't currently have VP9 support on https://github.com/alfg/mp4-rust, but I'll look into adding it soon so it can be supported in this project as well.

Thanks!

**Comment by alfg** [comment]
Hi @nintha, 

Thanks to your work on https://github.com/alfg/mp4-rust/pull/41, I have updated [mp4-inspector](https://alfg.github.io/mp4-inspector/) with the latest from master and it now works with vp9.

![Capture](https://user-images.githubusercontent.com/702541/105943242-b90abb00-6015-11eb-9072-e6584e7ec4f3.PNG)

Feel free to try it out and close the issue if resolved. 

Thanks!

**Comment by nintha** [comment]
Hi @alfg 

I tested a mp4 file with vp9, that worked well. However, I uploaded a fragmented mp4 with vp9, then it printed some same error in the console.

I used following commands to generate fragmented mp4 file.
```
ffmpeg -i ad_vp9.mp4 -f mp4 -movflags frag_keyframe+empty_moov ad_vp9_fmp4.mp4
```

I copy the test file link as an attachment.

https://user-images.githubusercontent.com/22030293/105712401-b1cfa880-5f54-11eb-9f92-2a31495bb709.mp4

**Comment by alfg** [comment]
Hey @nintha, 

I tried the file you provided in the attachment, and it seems to work OK. However, it seems to be an avc1 encoded video.

I converted the file using:
```
ffmpeg -i ad_vp9.mp4 -f mp4 -movflags frag_keyframe+empty_moov ad_vp9_fmp4.mp4
```

And now it failed. It also failed when using `mp4-rust`'s `mp4sample` example:
```
cargo run --example mp4sample ad_vp9_fmp4.mp4
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })', examples\mp4sample.rs:37:37
```

So it seems there's still an issue parsing this file in the `mp4-rust` package.

**Comment by nintha** [comment]
The link of attachment is same as which in https://github.com/alfg/mp4-rust/pull/41. The issue may be only effected by   fragmented mp4. 

`sample_offset()` return a error value. Does the `TrunBox` lack some fields?

https://github.com/alfg/mp4-rust/blob/2a33b990e623e6648e798d91cca048bdd51a7d9b/src/track.rs#L415-L418

**Comment by nintha** [comment]
I create a new PR. https://github.com/alfg/mp4-rust/pull/46

 I have tested mp4-inspector with the PR version and it now works with fragmented mp4.
![image](https://user-images.githubusercontent.com/22030293/106007609-74545200-60f1-11eb-9023-4f0d16f29dc3.png)

**Comment by alfg** [comment]
Thanks. I've added some comments on the PR for `mp4-rust`.

**Comment by alfg** [comment]
@nintha https://alfg.github.io/mp4-inspector/ is updated with latest from master `mp4-rust`. Try it out when you have a moment. Thanks!

**Comment by nintha** [comment]
Thanks @alfg. Everything is ok.

**Comment by alfg** [comment]
Thanks for confirming!
